language: python
python:
  - 2.7
  - 3.6
env:
  - DJANGO=Django==1.11.0
install:
  - pip install $DJANGO
  - pip install mock==1.0.1 coverage==3.7.1 coveralls==0.4.1
script:
  - coverage run --source=django_test_mixins.py tests.py
after_success:
  coveralls
deploy:
  provider: pypi
  user: wilfredh
  password:
    secure: LkJ8DY2/rl+faltecO9GXz0Lu3W9GLtCf0vV7YIsIxlNm+nwP3fDQ8aWvdUDoYhXCuCjyY3P4W1ZACMGYqD8tWCP/Q91TiDelJ3cWsSudvpC3npZ9d+44jiJctBvrvrnKtka7/El16YXFn5OwWK+KCRW2SwnW17I4A+7t3Nof40=
  on:
    tags: true
    python: 3.6
    repo: Wilfred/django-test-mixins
    all_branches: true

notifications:
  email: false
